/** RDS IAM database authentication.
 *
 * `getRdsAuthToken()` returns a short-lived (15-minute) connection token
 * generated by signing a connect request with the caller's IAM
 * credentials. The token is used as the Postgres password. No static
 * credential exists on the runtime path — RDS rotating the master
 * password no longer affects running app tasks, because the app
 * doesn't use the master password at all.
 *
 * Token cache: tokens take ~10ms to generate (a local sigv4 sign — no
 * network round-trip) and last 15 minutes. We cache for 13 minutes
 * keyed by (host, port, user) so the per-connection callback in
 * `pg.Pool` doesn't re-sign on every connect attempt. The 2-minute
 * margin protects against a token being handed out at minute 14:59,
 * still in flight when the server rejects it at 15:00.
 *
 * SSL: IAM auth REQUIRES TLS. The RDS Global CA bundle is shipped in
 * the container at `/app/rds-global-bundle.pem`
 * (see Dockerfile) — load once at module init. `verify-full` chain
 * validation replaces the legacy `sslmode=require` (encrypt-but-don't-
 * verify) workaround the static-password code path used to settle for.
 *
 * Local dev: this module is never imported when
 * `DANTE_USE_IAM_DB_AUTH` is unset. `lib/db/client.ts` and
 * `lib/sync/db.ts` both branch on that env var. */
import fs from "node:fs";

import { Signer } from "@aws-sdk/rds-signer";

const TOKEN_TTL_MS = 13 * 60 * 1000;

type CachedToken = { token: string; expires_at: number };
const tokenCache = new Map<string, CachedToken>();

/** Generate (or reuse a cached) IAM auth token for an RDS connect.
 * Cache key is `host|port|user` so two pools (app + an in-process
 * sync) targeting different DB users share the cache cleanly. */
export async function getRdsAuthToken(
  host: string,
  port: number,
  user: string,
): Promise<string> {
  const key = `${host}|${port}|${user}`;
  const now = Date.now();
  const hit = tokenCache.get(key);
  if (hit && hit.expires_at > now) return hit.token;
  const region = process.env.AWS_REGION ?? process.env.AWS_DEFAULT_REGION;
  if (!region) {
    throw new Error(
      "RDS IAM auth: AWS_REGION not set. The Lambda runtime injects it " +
        "automatically; on ECS the task definition must set it explicitly.",
    );
  }
  const signer = new Signer({ hostname: host, port, username: user, region });
  const token = await signer.getAuthToken();
  tokenCache.set(key, { token, expires_at: now + TOKEN_TTL_MS });
  return token;
}

/** RDS Global CA bundle path. Overridable for tests / alternative
 * deploys. Default is the Dockerfile install location. */
const CA_BUNDLE_PATH =
  process.env.DANTE_RDS_CA_BUNDLE_PATH ?? "/app/rds-global-bundle.pem";

let cachedCa: Buffer | null = null;

/** Returns the RDS Global CA bundle as a Buffer for use as
 * `ssl.ca` in pg / pg.Pool config. Cached after first read. */
export function getRdsCaBundle(): Buffer {
  if (cachedCa !== null) return cachedCa;
  cachedCa = fs.readFileSync(CA_BUNDLE_PATH);
  return cachedCa;
}

/** Parse an endpoint string of the shape `host:port` or `host` into
 * `{host, port}`. Used by both client.ts and sync/db.ts to interpret
 * `DANTE_DATABASE_ENDPOINT`. */
export function parseDatabaseEndpoint(endpoint: string): {
  host: string;
  port: number;
} {
  const idx = endpoint.lastIndexOf(":");
  if (idx === -1) return { host: endpoint, port: 5432 };
  const host = endpoint.slice(0, idx);
  const port = Number.parseInt(endpoint.slice(idx + 1), 10);
  return { host, port: Number.isFinite(port) && port > 0 ? port : 5432 };
}

/** True when the runtime should use IAM auth. Both pool / client
 * builders branch on this. */
export function useIamDbAuth(): boolean {
  return process.env.DANTE_USE_IAM_DB_AUTH === "1";
}
