CREATE TABLE "awork_company" (
	"awork_company_id" text PRIMARY KEY NOT NULL,
	"name" text,
	"is_external" boolean,
	"projects_count" integer,
	"projects_in_progress_count" integer,
	"created_on" timestamp,
	"updated_on" timestamp,
	"last_seen_sync_run_id" integer,
	"last_updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "awork_company_link" (
	"awork_company_id" text PRIMARY KEY NOT NULL,
	"customer_id" integer NOT NULL,
	"mapped_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "awork_project" (
	"awork_project_id" text PRIMARY KEY NOT NULL,
	"name" text,
	"project_key" text,
	"awork_company_id" text,
	"is_billable_by_default" boolean,
	"is_external" boolean,
	"is_private" boolean,
	"is_retainer" boolean,
	"project_status_id" text,
	"description" text,
	"tasks_count" integer,
	"tasks_done_count" integer,
	"created_on" timestamp,
	"updated_on" timestamp,
	"last_seen_sync_run_id" integer,
	"last_updated_at" timestamp,
	"start_date" date,
	"due_date" date,
	"closed_on" date,
	"time_budget_seconds" bigint,
	"project_status_type" text,
	"project_status_name" text,
	"daily_rate_eur" numeric(12, 2),
	"fixed_price_eur" numeric(12, 2),
	"order_number" text
);
--> statement-breakpoint
CREATE TABLE "awork_project_link" (
	"awork_project_id" text PRIMARY KEY NOT NULL,
	"project_id" integer NOT NULL,
	"mapped_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "awork_time_entry" (
	"awork_time_entry_id" text PRIMARY KEY NOT NULL,
	"awork_user_id" text,
	"awork_project_id" text,
	"awork_task_id" text,
	"work_date" date,
	"duration_seconds" integer,
	"duration_minutes" integer,
	"is_billable" boolean,
	"is_billed" boolean,
	"note" text,
	"type_of_work_id" text,
	"type_of_work_name" text,
	"start_date_utc" timestamp,
	"end_date_utc" timestamp,
	"last_seen_sync_run_id" integer
);
--> statement-breakpoint
CREATE TABLE "awork_user" (
	"awork_user_id" text PRIMARY KEY NOT NULL,
	"first_name" text,
	"last_name" text,
	"email" text,
	"position" text,
	"title" text,
	"is_agent" boolean,
	"is_archived" boolean,
	"is_deactivated" boolean,
	"is_external" boolean,
	"status" text,
	"created_on" timestamp,
	"last_seen_sync_run_id" integer,
	"last_updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "awork_user_link" (
	"awork_user_id" text PRIMARY KEY NOT NULL,
	"employee_id" integer NOT NULL,
	"mapped_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignment" (
	"assignment_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignment_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer,
	"freelancer_id" integer,
	"project_id" integer NOT NULL,
	"profile" text,
	"allocation_pct" numeric(5, 4) DEFAULT '1.0' NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date,
	"daily_rate_override_eur" numeric(10, 2),
	"daily_cost_override_eur" numeric(10, 2),
	"notes" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customer" (
	"customer_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"notes" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "customer_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "framework_agreement" (
	"framework_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "framework_agreement_framework_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"name" text NOT NULL,
	"start_date" date,
	"end_date" date,
	"notes" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "uq_framework_customer_name" UNIQUE("customer_id","name")
);
--> statement-breakpoint
CREATE TABLE "framework_rate" (
	"framework_id" integer NOT NULL,
	"profile" text NOT NULL,
	"valid_from" date NOT NULL,
	"daily_rate_eur" numeric(10, 2) NOT NULL,
	CONSTRAINT "framework_rate_framework_id_profile_valid_from_pk" PRIMARY KEY("framework_id","profile","valid_from")
);
--> statement-breakpoint
CREATE TABLE "freelancer" (
	"freelancer_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "freelancer_freelancer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"daily_cost_eur" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"contact_email" text,
	"notes" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "freelancer_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "project" (
	"project_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"framework_id" integer,
	"name" text NOT NULL,
	"billing_model" text NOT NULL,
	"agreed_amount_eur" numeric(12, 2),
	"planned_start_date" date,
	"planned_end_date" date,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"time_budget_hours" integer,
	CONSTRAINT "uq_project_customer_name" UNIQUE("customer_id","name")
);
--> statement-breakpoint
CREATE TABLE "project_rate" (
	"project_id" integer NOT NULL,
	"profile" text NOT NULL,
	"valid_from" date NOT NULL,
	"daily_rate_eur" numeric(10, 2) NOT NULL,
	CONSTRAINT "project_rate_project_id_profile_valid_from_pk" PRIMARY KEY("project_id","profile","valid_from")
);
--> statement-breakpoint
CREATE TABLE "setting" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compensation_event" (
	"compensation_id" text PRIMARY KEY NOT NULL,
	"employee_id" integer NOT NULL,
	"effective_from" date,
	"amount_value" numeric(12, 2),
	"amount_currency" text,
	"interval" text,
	"category" text,
	"type_name" text,
	"legal_entity_id" text,
	"weekly_working_hours" double precision,
	"full_time_weekly_working_hours" double precision,
	"last_seen_sync_run_id" integer NOT NULL,
	"last_updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employee_annotation" (
	"employee_id" integer PRIMARY KEY NOT NULL,
	"team_user" text,
	"is_multi_org" boolean,
	"is_real_employee" boolean,
	"is_project_contributing" boolean,
	"role_tier" text,
	"last_reconciled_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employee_current" (
	"employee_id" integer PRIMARY KEY NOT NULL,
	"first_name" text,
	"last_name" text,
	"email" text,
	"status" text,
	"department" text,
	"position" text,
	"subcompany" text,
	"office" text,
	"hire_date" date,
	"contract_end_date" date,
	"employment_end_date" date,
	"employment_type" text,
	"weekly_working_hours" double precision,
	"supervisor_id" integer,
	"fix_salary" numeric(12, 2),
	"fix_salary_interval" text,
	"hourly_salary" numeric(12, 2),
	"cost_center" text,
	"gender" text,
	"probation_period_end" date,
	"birth_date" date,
	"nationality" text,
	"notice_period_probation" text,
	"absence_entitlement" text,
	"last_seen_sync_run_id" integer NOT NULL,
	"last_updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employee_history" (
	"history_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employee_history_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"field_name" text NOT NULL,
	"field_value" text,
	"valid_from" timestamp NOT NULL,
	"valid_to" timestamp,
	"is_current" boolean NOT NULL,
	"sync_run_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "salary_change_event" (
	"event_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "salary_change_event_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"effective_date" date NOT NULL,
	"old_annual_eur" numeric(12, 2),
	"new_annual_eur" numeric(12, 2),
	"source" text NOT NULL,
	CONSTRAINT "uq_salary_event" UNIQUE("employee_id","effective_date","new_annual_eur")
);
--> statement-breakpoint
CREATE TABLE "team" (
	"team_name" text PRIMARY KEY NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raw_employee_snapshot" (
	"sync_run_id" integer NOT NULL,
	"employee_id" integer NOT NULL,
	"payload" jsonb NOT NULL,
	CONSTRAINT "raw_employee_snapshot_sync_run_id_employee_id_pk" PRIMARY KEY("sync_run_id","employee_id")
);
--> statement-breakpoint
CREATE TABLE "sync_run" (
	"sync_run_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_run_sync_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"started_at" timestamp NOT NULL,
	"completed_at" timestamp,
	"employees_seen" integer,
	"status" text NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "absence" (
	"absence_id" bigint PRIMARY KEY NOT NULL,
	"employee_id" integer NOT NULL,
	"time_off_type" text,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"half_day_start" boolean,
	"half_day_end" boolean,
	"days_count" double precision,
	"status" text,
	"comment" text,
	"last_seen_sync_run_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attendance" (
	"attendance_id" bigint PRIMARY KEY NOT NULL,
	"employee_id" integer NOT NULL,
	"work_date" date NOT NULL,
	"start_time" text,
	"end_time" text,
	"break_minutes" integer,
	"duration_minutes" integer,
	"project_id" integer,
	"comment" text,
	"last_seen_sync_run_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "personio_project" (
	"personio_project_id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"active" boolean,
	"last_seen_sync_run_id" integer,
	"last_updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "personio_project_link" (
	"personio_project_id" integer PRIMARY KEY NOT NULL,
	"project_id" integer NOT NULL,
	"mapped_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_history_employee_field_current" ON "employee_history" USING btree ("employee_id","field_name","is_current");